### ISSUE TITLE
SWI-Prolog fails to build with Java version 8

### ISSUE THREAD

**Issue by jessealama** [SWI-Prolog/issues#1]
When Java 8 is installed, there are some difficulties in the build (I'm working with version 6.6.5) dealing with the JPL docs:

```
"jar" cf ../../jpl.jar jpl/Atom.class  jpl/Compound.class
jpl/Float.class  jpl/Integer.class  jpl/JRef.class
jpl/JPLException.class  jpl/JPL.class  jpl/PrologException.class
jpl/Query.class  jpl/Term.class  jpl/Util.class  jpl/Variable.class
jpl/Version.class  jpl/fli/atom_t.class  jpl/fli/BooleanHolder.class
jpl/fli/DoubleHolder.class  jpl/fli/engine_t.class  jpl/fli/fid_t.class
  jpl/fli/functor_t.class  jpl/fli/IntHolder.class
jpl/fli/Int64Holder.class  jpl/fli/LongHolder.class
jpl/fli/module_t.class  jpl/fli/ObjectHolder.class
jpl/fli/PointerHolder.class  jpl/fli/predicate_t.class
jpl/fli/Prolog.class  jpl/fli/qid_t.class  jpl/fli/StringHolder.class
jpl/fli/term_t.class
jpl/fli/atom_t.java:38: error: block element not allowed within inline
element <i>: p
  * Copyright (C) 1998  Fred Dushin<p>
                                   ^
jpl/fli/atom_t.java:43: error: tag not allowed here: <p>
  * of the License, or (at your option) any later version.<p>
                                                          ^
jpl/fli/atom_t.java:48: error: tag not allowed here: <p>
  * GNU Library Public License for more details.<p>
                                                ^
jpl/fli/atom_t.java:50: error: malformed HTML
  * @author  Fred Dushin <fadushin@syr.edu>
                         ^
jpl/fli/atom_t.java:50: error: bad use of '>'
  * @author  Fred Dushin <fadushin@syr.edu>
                                          ^
Generating ../../docs/java_api/javadoc/jpl/fli/BooleanHolder.html...
jpl/fli/BooleanHolder.java:37: error: block element not allowed within
inline element <i>: p
  * Copyright (C) 1998  Fred Dushin<p>
                                   ^
jpl/fli/BooleanHolder.java:42: error: tag not allowed here: <p>
  * of the License, or (at your option) any later version.<p>
                                                          ^
jpl/fli/BooleanHolder.java:47: error: tag not allowed here: <p>
  * GNU Library Public License for more details.<p>
                                                ^
jpl/fli/BooleanHolder.java:49: error: malformed HTML
  * @author  Fred Dushin <fadushin@syr.edu>
                         ^
jpl/fli/BooleanHolder.java:49: error: bad use of '>'
  * @author  Fred Dushin <fadushin@syr.edu>
                                          ^
Generating ../../docs/java_api/javadoc/jpl/fli/DoubleHolder.html...
jpl/fli/DoubleHolder.java:37: error: block element not allowed within
inline element <i>: p
  * Copyright (C) 1998  Fred Dushin<p>
                                   ^
jpl/fli/DoubleHolder.java:42: error: tag not allowed here: <p>
  * of the License, or (at your option) any later version.<p>
                                                          ^
jpl/fli/DoubleHolder.java:47: error: tag not allowed here: <p>
  * GNU Library Public License for more details.<p>
                                                ^
jpl/fli/DoubleHolder.java:49: error: malformed HTML
  * @author  Fred Dushin <fadushin@syr.edu>
                         ^
jpl/fli/DoubleHolder.java:49: error: bad use of '>'
  * @author  Fred Dushin <fadushin@syr.edu>
                                          ^
Generating ../../docs/java_api/javadoc/jpl/fli/engine_t.html...
jpl/fli/engine_t.java:35: error: block element not allowed within
inline element <i>: p
  * Copyright (C) 1998  Fred Dushin<p>
```

(and many more errors similar to these).  The difficulty seems to be that Java 8 strictly enforces Javadoc comment styles, unlike Java 7.
